lib/tilt.rb
test/tilt_cache_test.rb

This avoids calling the block again with the same arguments and having it
do some possibly expensive processing only to return nil again.
Sorry if this is a frequently requested pull.

Make Tilt::Cache return nil when nil is found in the cache.

---

lib/tilt/template.rb

Currently, tilt uses the value of Hash#keys directly as the cache
key.  On ruby 1.8 this results in 2^N possible cache entries for
the template, where N is the number of keys in locals, because
Hash#keys returns the keys in an arbitrary order on 1.8.
Even on 1.9, where Hash#keys returns the keys in entry order,
this can cause similar issues unless user code always enters the
keys in the hash in the same order.
I chose to put this code in evaluate instead of compiled_method
itself, because evaluate creates the array and can use sort!
to sort it.  If done in compiled_method, locals_keys is the
argument, and mutating arguments is generally a bad API practice,
so you'd have to use sort, which would cause an extra array
allocation.

Sort locals_keys before looking up template in @compiled_method

---

test/tilt_wikiclothtemplate_test.rb

The fix is very simple. Added m to the regex to match on new lines by replacing
/<h1>.*Hello World!.*<\/h1>/
with
/<h1>.*Hello World!.*<\/h1>/m
This fixes the regex failing to match on leading and trailing newlines.

Fixes for failing tests for wikicloth.

---

lib/tilt/haml.rb
lib/tilt/template.rb
test/tilt_hamltemplate_test.rb
test/tilt_template_test.rb

To reproduce:
```ruby
require 'tilt'
t = Tilt::HamlTemplate.new do
'%h1'
end
p t.render(nil)
```
**Output: Ruby 2.1**:
```
<h1></h1>
```
**Output: Ruby 2.2**:
```
(__TEMPLATE__):4:in `ensure in block in singleton class': undefined method `upper' for nil:NilClass (NoMethodError)
from (__TEMPLATE__):4:in `block in singleton class'
from (__TEMPLATE__):-9:in `instance_eval'
from (__TEMPLATE__):-9:in `singleton class'
from (__TEMPLATE__):-11:in `__tilt_70265677939160'
from /Users/alexbcoles/.gem/ruby/2.2.0/gems/tilt-2.0.1/lib/tilt/template.rb:155:in `call'
from /Users/alexbcoles/.gem/ruby/2.2.0/gems/tilt-2.0.1/lib/tilt/template.rb:155:in `evaluate'
from /Users/alexbcoles/.gem/ruby/2.2.0/gems/tilt-2.0.1/lib/tilt/haml.rb:17:in `evaluate'
from …
```

Ruby 2.2: Tilt::HamlTemplate#render shouldn't blow up on explicit nil

---

README.md

Minor fix in 'Basic Usage' example.

---

lib/tilt/csv.rb
test/tilt_csv_test.rb

Now it is possible to pass options (such as 'col_sep') directly to
csv engine.
In addition, if 'outvar' option is present, template output will be
stored in the provided variable.

Allow passing outvar and csv options.

---

lib/tilt/redcarpet.rb
test/tilt_markdown_test.rb

Fixes [Redcarpet render options](https://github.com/vmg/redcarpet#darling-i-packed-you-a-couple-renderers-for-lunch) which weren't being passed along. Re-added the `escape_html` test, which is one of the render options. Also related #238.

Add support for Redcarpet render options.

---

lib/tilt/babel.rb

Before the v2.0.1, I have my BabelTemplate implementation. But when the v2.0.2 released, my gem failed with:
```bash
/Users/saito/.rvm/gems/ruby-2.3.0/gems/linner-0.11.2/lib/linner/template.rb:17:in `<module:Tilt>': superclass mismatch for class BabelTemplate (TypeError)
from /Users/saito/.rvm/gems/ruby-2.3.0/gems/linner-0.11.2/lib/linner/template.rb:8:in `<top (required)>'
from /Users/saito/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
from /Users/saito/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
from /Users/saito/.rvm/gems/ruby-2.3.0/gems/linner-0.11.2/lib/linner.rb:11:in `<top (required)>'
from /Users/saito/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:120:in `require' …
```

Add mimetype to BabelTemplate

---

Gemfile
README.md
docs/TEMPLATES.md
lib/tilt.rb
lib/tilt/pandoc.rb
test/tilt_markdown_test.rb
test/tilt_pandoctemplate_test.rb

I need Pandoc in my Rails project. This is my attempt to register Pandoc as markdown parser in Tilt.
Any improvements are very welcome.
Here's the original question which made me create this PR: [Slim template: use Pandoc as markdown converter?](http://stackoverflow.com/questions/30058230/slim-template-use-pandoc-as-markdown-converter)
The tests aren't all passing yet. In fact, I'm a bit unsure on how to proceed, because of the following questions:
- As the used `pandoc-ruby` gem is only a wrapper for the `$ pandoc` command line tool, I'm unsure whether somehow it should be checked whether pandoc is installed on the system or not. Maybe `pandoc-ruby` does this already?
- Pandoc has a huge amount of special features. For examples, I love the …

Add pandoc support

---

lib/tilt/liquid.rb

Enable `line_numbers` by default to provide line information in Liquid errors.

Add options to Liquid template

---

lib/tilt/liquid.rb
test/tilt_liquidtemplate_test.rb

Ref #298 - Adds a test for overwriting default Liquid options/passing other options.
**Note:** Travis build failed due to RubyGems.org downtime

Add Liquid options tests

---

test/tilt_asciidoctor_test.rb
test/tilt_blueclothtemplate_test.rb
test/tilt_coffeescripttemplate_test.rb
test/tilt_commonmarkertemplate_test.rb
test/tilt_creoletemplate_test.rb
test/tilt_csv_test.rb
test/tilt_erbtemplate_test.rb
test/tilt_erubistemplate_test.rb
test/tilt_etannitemplate_test.rb
test/tilt_hamltemplate_test.rb
test/tilt_kramdown_test.rb
test/tilt_lesstemplate_test.rb
test/tilt_liquidtemplate_test.rb
test/tilt_livescripttemplate_test.rb
test/tilt_mapping_test.rb
test/tilt_markaby_test.rb
test/tilt_markdown_test.rb
test/tilt_marukutemplate_test.rb
test/tilt_pandoctemplate_test.rb
test/tilt_prawntemplate_test.rb
test/tilt_radiustemplate_test.rb
test/tilt_rdiscounttemplate_test.rb
test/tilt_rdoctemplate_test.rb
test/tilt_redcarpettemplate_test.rb
test/tilt_redclothtemplate_test.rb
test/tilt_rstpandoctemplate_test.rb
test/tilt_sasstemplate_test.rb
test/tilt_stringtemplate_test.rb
test/tilt_typescript_test.rb
test/tilt_wikiclothtemplate_test.rb

Here's an attempt to eliminate all ruby warnings in this repo.
We still see so many warnings from other bundled libraries, but I believe it's a good habit to at least keep our code base warning-free.

Ruby warnings in the tests

---

lib/tilt/template.rb
test/tilt_template_test.rb

Fixes issues when mixing string locals with symbol locals.

Always sort locals by strings (Fixes #306)

---

README.md
lib/tilt.rb
lib/tilt/erubi.rb
test/tilt_erubitemplate_test.rb

Erubi is a simplified fork of Erubis with the following advantages:
* Handles postfix conditionals when using escaping (e.g. <tt><%= foo if bar %></tt>)
* Works with ruby's --enable-frozen-string-literal option
* Automatically freezes strings for template text when ruby optimizes it (on ruby 2.1+)
* Escapes ' (apostrophe) when escaping for better XSS protection
* Has 88% smaller memory footprint for base engine
* Has 75% smaller memory footprint for tilt support
* Does no monkey patching (Erubis adds a method to Kernel)
* Has simpler internals (1 file, <150 lines of code)
* Has an open development model (Erubis doesn't have a public source control repository or bug tracker)
* Is not dead (Erubis hasn't been updated since 2011)
With this patch, Erubi will be tried before Erubis and ERB. …

Add support for Erubi template engine for erb and rhtml files

---

lib/tilt/template.rb

Starting in ruby 2.0, you can unbind methods from modules and
bind them to any object, and then call them.  There is no reason
to modify the BasicObject class in this case.
This fixes tilt's template compilation on ruby 2.0+ when BasicObject
is frozen.

Do not modify BasicObject during template compilation on ruby 2.0+

---

Gemfile

The error occurs when we do HACKING because removed deprecated method named `last_comment` in rake >= 12.0.0.
```
$ rake
rake aborted!
NoMethodError: undefined method `last_comment' for #<Rake::Application:0x007f88cb4b7e58>
```

Update yard for had unsupported last_comment method in rake

---

Gemfile
lib/tilt/haml.rb

Fixes https://github.com/rtomayko/tilt/issues/311
In https://github.com/haml/haml/pull/896, I've already implemented API exactly for this issue. After this change is released by tilt, I'll change Haml to depend on tilt after that version. Hopefully it'll be Haml 5.0.0.

Use Haml 5's new API to avoid using deprecated private method.

---

lib/tilt/template.rb

Without this dirty hack, ruby emits "assigned but unused variable - locals" warning in VERBOSE mode when no locals are given.
Following is a oneliner that reproduces the warning:
```
% ruby -rtilt -we "Tilt::ERBTemplate.new('test.erb', 11) { '' }.render"
test.erb:3: warning: assigned but unused variable - locals
```

Suppress "assigned but unused variable - locals" warning

---

lib/tilt/haml.rb

Fix #316.
ERB, Erubis and Slim solves the problem in Tilt layer. Then Haml follows it.
This is intended to be the same as https://github.com/judofyr/temple/blob/v0.8.0/lib/temple/templates/tilt.rb#L26-L29.
Actually it won't affect Haml 5 for now but I'll change Haml's generator to follow Temple's default option later. 
Since it's supported by `Temple::Engine` level, this change will fix warning without changing Haml.

Set buffer options from outvar option by Sinatra

---

lib/tilt/haml.rb

Hi, and thanks for maintaining this library.
I'm polishing the test suite of Sinatra, trying to get it to have less warning output.
The [precompiled_preamble](https://github.com/rtomayko/tilt/blob/8e53a8c7b12c61a6698695f8b7f0fa83619512f3/lib/tilt/haml.rb#L65), has this line:
```ruby
_hamlout = @haml_buffer = Haml::Buffer.new(@haml_buffer, #{options_for_buffer.inspect})
```
Can it be the cause of these Ruby warnings?
> warning: instance variable @haml_buffer not initialized
I wonder if it could be remedied with a change to
```ruby
_hamlout = @haml_buffer = Haml::Buffer.new(haml_buffer, #{options_for_buffer.inspect})
```
See code for [`haml_buffer`](https://github.com/haml/haml/blob/b61c6bc2c53e8a5d3c11e2d76c7cfde75cf941ab/lib/haml/helpers.rb#L674-L679).
Does this change make sense to you?

Avoid uninitialized instance var @haml_buffer

---

Rakefile
tilt.gemspec

First of all, thanks for Tilt!
This PR slims down the bundled gem by ~60% by:
- removing the `test_files` declaration (which is [deprecated](https://github.com/rubygems/guides/issues/90))
- removing all files which aren't required to build the gem from the `files` declaration. This is pretty standard practice
The same saving is a big percentage but small in absolute terms (30KB different in the `.gem`). Hopefully that's still worth having since this gem is downloaded millions of times.

Remove test files from bundled gem

---

lib/tilt/template.rb
test/tilt_template_test.rb

This fixes the following warning:
```
warning: `yield' in class syntax will not be supported from Ruby 3.0. [Feature #15575].
```
Considering that yield is how layout templates work in Tilt, I think this is an important change to allow people to start testing their applications that use Tilt with ruby 2.7.0-preview1.

Fix warning on Ruby 2.7 when using yield in templates

---

lib/tilt/template.rb
test/tilt_template_test.rb

There are a couple of issues here.  One is that BasicObjects do
not respond to is_a?.  Another is that they don't respond to
class.
To handle the class issue, use a case statement to separate
BasicObject from Object, and bind a Kernel method to the BasicObject
instance to be able to get the class.  Note that this does not work
on Ruby 1.9, and on Ruby 1.9, there is not a way to correctly get
the scope class.  Use Object in that case so things don't completely
break (though constant lookup will not use use the scope class).
While we don't need to handle is_a? after that change, still switch
from scope.is_a?(Module) to Module === scope, as that handles cases
where is_a? is redefined.
Related to #347

Handle rendering BasicObject instances

---

docs/TEMPLATES.md

For whatever reason, the Daring Fireball documentation site doesn't load if the URL contains a trailing slash. 
I'm sure this is a simple configuration on their webserver end to make, but for now new Tilt users looking to view the documentation will be presented with a 404 page.
This PR fixes that by removing the trailing slash.
Before: https://daringfireball.net/projects/markdown/syntax/
After: https://daringfireball.net/projects/markdown/syntax

Fix markdown documentation 404

---

tilt.gemspec

This reduces unnecessary redirection from http://... to https://... when someone visits this gem's homepage via https://rubygems.org/gems/tilt or some tools or APIs that use the gem's metadata.

GitHub is HTTPS by default

---

lib/tilt/csv.rb

This fixes issues such as:
~~~
1) Error:
CSVTemplateTest#test_compiles_and_evaluates_the_template_on_render:
TypeError: no implicit conversion of Hash into String
/usr/share/ruby/csv.rb:1273:in `initialize'
/usr/share/ruby/csv.rb:1273:in `new'
/usr/share/ruby/csv.rb:1273:in `generate'
(__TEMPLATE__):in `__tilt_920'
/builddir/build/BUILD/tilt-2.0.10/usr/share/gems/gems/tilt-2.0.10/lib/tilt/template.rb:170:in `call'
/builddir/build/BUILD/tilt-2.0.10/usr/share/gems/gems/tilt-2.0.10/lib/tilt/template.rb:170:in `evaluate'
/builddir/build/BUILD/tilt-2.0.10/usr/share/gems/gems/tilt-2.0.10/lib/tilt/template.rb:109:in `render'
/builddir/build/BUILD/tilt-2.0.10/usr/share/gems/gems/tilt-2.0.10/test/tilt_csv_test.rb:15:in `block in <class:CSVTemplateTest>'
~~~

Fix Ruby 3.0 compatibility.

---

docs/TEMPLATES.md
lib/tilt/commonmarker.rb
test/tilt_commonmarkertemplate_test.rb

Updated to match v0.21.2: https://github.com/gjtorikian/commonmarker

Allow all options and extensions available in CommonMarker

---

README.md
lib/tilt.rb

Add Tilt::EmacsOrg support

---

.github/workflows/test.yml
Gemfile
lib/tilt/pandoc.rb
lib/tilt/rst-pandoc.rb
test/test_helper.rb
test/tilt_asciidoctor_test.rb
test/tilt_commonmarkertemplate_test.rb
test/tilt_etannitemplate_test.rb
test/tilt_pandoctemplate_test.rb
test/tilt_stringtemplate_test.rb

This is in order to prepare a new release.
@ntkme: Could you have a look at this and see if it makes sense?
Pending work to make all tests work:

Switch over to GitHub Actions and fix various issues with the test suite

---

Rakefile

Also remove release task, since it uses rubyforge, which is no
longer around.
It seems unlikely anyone would be using the .tar.gz file, since
it is no longer uploaded to rubyforge.

Remove creation of .tar.gz file when building gem

---

Rakefile
lib/tilt/csv.rb
lib/tilt/erb.rb
lib/tilt/erubis.rb
lib/tilt/template.rb
test/tilt_radiustemplate_test.rb
test/tilt_template_test.rb
tilt.gemspec

At least some parts of tilt now require Ruby 2.0.0 (at least since
b1329a8a4883f0e08b12f1e639922105d3234438).
Remove specification_version, as rubygems states:
"Do not set this, it is set automatically when the gem is packaged."
Remove required_rubygems_version, a requirement of >= 0 is the same
as no requirement.
Remove rubygems version, as it is wrong and has no effect.

Add required_ruby_version to gemspec

---

lib/tilt.rb

Remove support for external opal, since opal changed the API.
Fixes #323
Fixes #359

Add livescript extension for LiveScript and remove Opal support

---

lib/tilt/dummy.rb
lib/tilt/mapping.rb

This was used to test for broken autoload in JRuby 9.0.4.0 and
below. I've tested that JRuby 9.0.5.0 doesn't have broken
autoload.  I don't think we need to try supporting those old
JRuby versions anymore.
Fixes #364

Remove Tilt::Dummy

---

Gemfile
test/test_helper.rb
test/tilt_babeltemplate.rb
test/tilt_markdown_test.rb
test/tilt_template_test.rb

Also, DRY up some test code using with_default_encoding and
with_utf8_default_encoding helper methods, instead of updating
default encodings in setup/teardown blocks.  This makes sure
only the specific tests that need default encodings have them
set.

Remove more Ruby <2 compatibility code

---

lib/tilt.rb
lib/tilt/mapping.rb
lib/tilt/pipeline.rb
test/tilt_pipeline_test.rb

This makes it easy to combine multiple template engines into
a single processing pipeline, by taking the output of one
template and using it as the input to another template,
returning the final output as the result of the pipeline.
As this is self contained, it could easily be implemented as
an external gem.  However, I think the functionality is useful
and you may want to ship it with Tilt, so I thought I'd send
a pull request here before trying to package it as an
external gem.

Add Tilt::Mapping#pipeline for handling template pipelines

---

Gemfile
lib/tilt/rst-pandoc.rb
test/tilt_markdown_test.rb
test/tilt_pandoctemplate_test.rb
test/tilt_rstpandoctemplate_test.rb

This makes sure all template engines other than bluecloth, less, and sigil are tested in CI.  Previously, the erubi and prawn engines were not tested (erubi not listed, prawn needs matrix in Ruby 3.1+).
This fixes some encoding issues in the pandoc tests when UTF-8 is no the default encoding.
This fixes the rst-pandoc template, which has been broken since the require was changed in a168cc9e7ae86c6e9769c4692ee7153b885906ef.  Update the rst-pandoc tests now that the :escape_html option works correctly.

Minor fixes

---

Gemfile
lib/tilt/bluecloth.rb
lib/tilt/less.rb
lib/tilt/sigil.rb

None of these are tested in CI.
BlueCloth conflicts with RDiscount.  It could theoretically be
tested in CI if RDiscount was in primary templates and BlueCloth
in secondary templates, but considering BlueCloth hasn't had a
release in over 10 years, and Tilt supports many other markdown
formats, there isn't a good reason to keep supporting it.
Less on CRuby depends on therubyracer, which no longer works on
modern Ruby due to changes in Psych.  I tried enabling it in CI,
and it won't install (https://github.com/jeremyevans/tilt/runs/7812514562?check_suite_focus=true#step:4:155).
Less hasn't had a release in over 8 years, and therubyracer hasn't
had a release in over 5 years.
Sigil doesn't have a gem, and isn't even packaged for my operating
system (OpenBSD).  It's possible we could test it …

Deprecate BlueCloth, Less, and Sigil support

---

.github/workflows/test.yml
CHANGELOG.md
Gemfile
README.md
Rakefile
lib/tilt.rb
lib/tilt/erb.rb
lib/tilt/erubi.rb
lib/tilt/erubis.rb
lib/tilt/template.rb
test/tilt_erbtemplate_test.rb
test/tilt_erubistemplate_test.rb
test/tilt_erubitemplate_test.rb
test/tilt_template_test.rb
tilt.gemspec

@judofyr since I know you are busy, this:
* Combines the #301, #380, #385, #393 pull requests (and also fixes issues #384, #390)
* Updates CI to include Ruby 3.2
* Updates the CHANGELOG
* Makes it so you do not need to regenerate the gemspec
* Bumps version to 2.1.0
After merging, you should be able to build the 2.1.0 gem for release.
Hopefully you can add also me as a gem owner and we can move the repository to something we can control.  There is still significant work I want to do on tilt, such as increasing test coverage, and it would be much easier if I had the ability to merge PRs or push.

Prepare for Tilt 2.1.0 Release
